### PR TITLE
perf: faster divup with no intermediate overflow

### PR DESCRIPTION
**Pull request by transmissions11**

### CODE REVIEW

**Comment by transmissions11** [comment]
Should be equivalent. Inspired by balancer, directly adapted from solmate

**Comment by transmissions11** [comment]
No need for add() or sub() in there because we check no underflow via the ternary, and overflow is not possible cuz we just divided

**Review by hexonaut — APPROVED** [review]
```
(x + y - 1) / y
= (x - 1) / y + y/y
= (x - 1) / y + 1
```

Cover the underflow case. Makes sense to me.

**Comment by hexonaut** [comment]
@kmbarry1 maybe you should double check this before we merge.

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Pull request merged**
